/* piconf.h.  Generated by configure.  */
/* piconf.h.in.  Generated from configure.ac by autoheader.  */

/* Enable debugging */
#define ENABLE_DEBUG 1

/* Enable common macros */
#define ENABLE_MACROS 

/* Whether the compile supports `bool' type */
/* #undef HAVE_BOOL */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "mtr@iki.fi"

/* Define to the full name of this package. */
#define PACKAGE_NAME "pi"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pi 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pi"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Optimize for runtime size */
/* #undef WITH_REALLY_SMALL_RUNTIME */
