FROM ubuntu:16.04
MAINTAINER Markku Rossi <markku.rossi@ssh.com>

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get update --fix-missing
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get update --fix-missing
RUN apt-get install -y gcc
RUN apt-get install -y make
RUN apt-get install -y less
RUN apt-get install -y vim

RUN apt-get install -y binutils-dev
RUN apt-get install -y pkg-config
